### ISSUE TITLE
about update

### ISSUE THREAD

**Issue by geminiyellow** [DaKaZ/react-native-vertical-tab-view#1]
hi @DaKaZ , thanks for your great job.
just one question, will this project update with `react-native-tab-view`?
i notice that, there is only 1 contributor, and have not update at the last pass month.

**Comment by DaKaZ** [comment]
Hi @geminiyellow - I tried to get the author of react-native-tab-view to accept these changes into the main library, but he rejected the work (see: https://github.com/react-native-community/react-native-tab-view/pull/587)  So I authored this library to use the majority of react-native-tab-view as a dependency.  This works very well so far and I have not needed any changes.  That said, PRs are always welcome if you find a bug or want to add a new feature.  Thanks

**Comment by DaKaZ** [comment]
Yeah, I would love for this package to be a sub-package of RNTV, but that option was not given to me.  No pride in authorship here... I hate having to maintain this separately, but I will as long as I need to.
